core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shortner.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shortner/urls.py
from django.urls import path
from . import views

app_name = 'shortener'
urlpatterns = [
    path('', views.index, name='index'),
    path('shorten/', views.shorten_url, name='shorten_url'),
    path('<short_code>/', views.redirect_original, name='redirect_original'),
    path('<short_code>/stats/', views.shorten_url_created, name='shorten_url_created'),
]

shortner/models.py
import random
import string

from django.db import models
from django.urls import reverse


def generate_short_code():
    """
    Generate a random 6 character code
    """
    short_code = ''.join(random.choices(string.ascii_lowercase + string.digits, k=6))
    return short_code


class ShortURL(models.Model):
    original_url = models.URLField(max_length=1000)
    short_code = models.CharField(max_length=15, unique=True, blank=True)
    num_clicks = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.original_url

    def get_short_url(self):
        return reverse('redirect_original', args=[self.short_code])

    def get_stats_url(self):
        return reverse('short_url_stats', args=[self.short_code])

    def save(self, *args, **kwargs):
        if not self.pk:
            # This code only runs if the object is being created for the first time
            self.short_code = generate_short_code()

        super().save(*args, **kwargs)

shortner/forms.py
from django import forms
from .models import ShortURL


class ShortURLForm(forms.ModelForm):
    class Meta:
        model = ShortURL
        fields = ['original_url']
        labels = {
            'original_url': 'لینک شما:'
        }
        widgets = {
            'original_url': forms.TextInput(attrs={'placeholder': 'لینک خودرا کوتاه کنید',
                                                   'class': 'form-control'})
        }

shortner/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import ShortURL
from .forms import ShortURLForm


def index(request):
    """
    Render index page with form for submitting URL
    """
    title = 'کوتاه کننده لینک'
    if request.method == 'POST':
        form = ShortURLForm(request.POST)
        if form.is_valid():
            url = form.cleaned_data['original_url']
            short_url = ShortURL(original_url=url)
            short_url.save()
            return redirect(reverse('shortener:shorten_url_created', args=[short_url.short_code]))
    else:
        form = ShortURLForm()

    return render(request, 'index.html', {'form': form, 'title': title})


def redirect_original(request, short_code):
    """
    Redirect to original URL based on short code
    """
    short_url = get_object_or_404(ShortURL, short_code=short_code)
    short_url.num_clicks += 1
    short_url.save()
    return redirect(short_url.original_url)


def shorten_url(request):
    """
    Render page with short URL created from original URL
    """
    short_url = None
    if request.method == 'POST':
        form = ShortURLForm(request.POST)
        if form.is_valid():
            url = form.cleaned_data['url']
            short_url = ShortURL(original_url=url)
            short_url.save()
            return redirect(reverse('stats', kwargs={'short_code': short_url.short_code}))

    form = ShortURLForm()
    return render(request, 'shorten.html', {'form': form, 'short_url': short_url})


def shorten_url_created(request, short_code):
    """
    Render page showing the original and shortened URLs, as well as the number of clicks
    """
    short_url = get_object_or_404(ShortURL, short_code=short_code)
    return render(request, 'stats.html', {'short_url': short_url})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.rtl.min.css" integrity="sha384-WJUUqfoMmnfkBLne5uxXj+na/c7sesSJ32gI7GfCk4zO4GthUKhSEGyvQ839BC51" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>



    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} خوش آمدید - کوتاه کننده لینک نمونه {% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}">


    {% block extra_css %}{% endblock %}
</head>
<body>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'shortener:index' %}">کوتاه کننده لینک نمونه</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shortener:index' %}">صفحه اصلی</a>
                </li>

            </ul>
        </div>
    </div>
</nav>

<!-- Content -->
<div class="container mt-4">
    {% block content %}{% endblock %}
</div>



<footer class="bg-dark py-3 text-light fixed-bottom">
  <div class="container">
    <div class="row">
      <div class="col-md-6 text-center text-md-start">
        <p>این سایت توسط محمدرضا صداقت طراحی شده است
        &copy;</p>
      </div>
      <div class="col-md-6 text-center text-md-end">
        <ul class="list-inline">
          <li class="list-inline-item"><a href="https://mrsdts.ir" target="_blank">MrSDTs</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

{% block extra_js %}{% endblock %}
</body>
</html>

templates/create_short_url.html
{% extends 'base.html' %}

{% block content %}
    <h2>Create a Short URL</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Shorten</button>
    </form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<div class="row justify-content-center">
<div class="col-md-8">
<div class="card">
<div class="card-header">{{ title }}</div>
<div class="card-body">
<form method="POST">
{% csrf_token %}
{{ form.as_p }}
<button class="btn btn-primary" type="submit">کوتاه کن</button>
</form>
</div>
</div>
</div>
</div>
</div>
{% endblock %}

templates/short_url_created.html
{% extends 'base.html' %}

{% block content %}
  <h1>URL Shortened</h1>
  <p>Here's your shortened URL:</p>
  <a href="{{ short_url }}">{{ short_url }}</a>
{% endblock %}

templates/shorten.html
{% extends 'base.html' %}

{% block content %}
  <h1>URL Shortened</h1>
  <p>Here's your shortened URL:</p>
  <a href="{{ short_url }}">{{ short_url }}</a>
{% endblock %}

templates/shortened.html
{% extends 'base.html' %}

{% block content %}
  <h1>URL Shortened</h1>
  <p>Here's your shortened URL:</p>
  <a href="{{ short_url }}">{{ short_url }}</a>
{% endblock %}

templates/stats.html
{% extends 'base.html' %}

{% block content %}
    <h2>لینک شما: <a href="{{ short_url.original_url }}">{{ short_url.original_url }}</a></h2>
    <h2>آدرس کوتاه شده: <a id="short-url" target="_blank" href="{{ request.scheme }}://{{ request.get_host }}/{{ short_url.short_code }}">{{ request.get_host }}/{{ short_url.short_code }}</a></h2>
    <h2>تعداد کلیک: {{ short_url.num_clicks }}</h2>
    <button id="copy-button" class="btn btn-primary">کپی کردن آدرس</button>




<div aria-live="polite" aria-atomic="true" class="bg-body-secondary position-relative bd-example-toasts rounded-3">
  <div class="toast-container p-3 " id="toastPlacement">
    <div id="toast" class="toast" data-delay="2500">
      <div class="toast-header">
        <img src="" class="rounded me-2" alt="">
        <strong class="me-auto">آدرس کوتاه شده کپی شد</strong>
      </div>
{#      <div class="toast-body text-center">#}
{#{{ request.get_host }}/{{ short_url.short_code }}#}
{#      </div>#}
    </div>
  </div>
</div>



<script>
  $(document).ready(function() {
    // Get the shortened URL from the HTML element with ID "short-url"
    var shortUrl = $('#short-url').text();

    // Create the full URL by appending the base URL to the shortened URL
    var fullUrl = shortUrl;

    // Add a click event listener to the button
    $('#copy-button').click(function() {
      // Create a temporary input element and append it to the body of the page
      var tempInput = $("<input>");
      $("body").append(tempInput);

      // Set the value of the temporary input element to the full URL
      tempInput.val(fullUrl).select();

      // Copy the value of the temporary input element to the clipboard
      document.execCommand("copy");

      // Remove the temporary input element from the page
      tempInput.remove();

    // Show a toast message to the user indicating that the URL has been copied to the clipboard
    var toast = $('#toast');
    var bsToast = new bootstrap.Toast(toast[0]);
    bsToast.show();

    });
  });
</script>

{% endblock %}